name: askbtc
favicon: null
layout_spectrum: 0.7795277335681021
typography_spectrum: 0.04096028255298734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6257228271570057
  lightness: 0.691713317995891
  saturation: 0.7291514244861901
  rhythmicContrast: 0.6067704656161368
purpose: []
